### PR TITLE
colin fixed our filter error

### PR DESCRIPTION
**Pull request by hajeraR**
api sole purpose has been completed

### CODE REVIEW

**Comment by DanaMurali** [comment]
I totally did it guys.....;)

**Comment by hajeraR** [comment]
> I totally did it guys.....;)

bullshit bruv

**Comment by TamaraHerrington** [comment]
Nice but do we have any merge conflicts????

**Comment by DanaMurali** [comment]
Jokes aside....Thank God for Colin!

**Comment by jordan-s99** [comment]
now we can try and filter by multiple allergies?

**Comment by DanaMurali** [comment]
> now we can try and filter by multiple allergies?

Do we though

**Review by TamaraHerrington — APPROVED** [review]

**Comment by TamaraHerrington** [comment]
Step awaaaaaay from the code!

**Pull request merged**
